[tool.poetry]
name = "src"
version = "0.1.0"
description = ""
authors = ["aaltonenn <joona.otso.aaltonen@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
invoke = "^2.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
